#!/bin/sh
NDK_BIN_DIR=$(dirname "$0")
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Linux
        HOST_SYSTEM_NAME="linux-x86_64"
        HOST_PYTHON=~/ndk/out/android-ndk-r24-canary/toolchains/llvm/prebuilt/$HOST_SYSTEM_NAME/python3/bin/python3
elif [[ "$OSTYPE" == "darwin"* ]]; then
        # Mac OSX
        HOST_SYSTEM_NAME="darwin-x86_64"
        HOST_PYTHON=~/ndk/out/android-ndk-r24-canary/toolchains/llvm/prebuilt/$HOST_SYSTEM_NAME/python3/bin/python3
else
        HOST_SYSTEM_NAME="windows-x86_64"
        HOST_PYTHON=~/ndk/out/android-ndk-r24-canary/toolchains/llvm/prebuilt/$HOST_SYSTEM_NAME/python3/python.exe
fi
${HOST_PYTHON} "${NDK_BIN_DIR}"/ndk-gdb.py "$@"
