# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kokoro_api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kokoro_api.proto',
  package='KokoroApi',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10kokoro_api.proto\x12\tKokoroApi\"2\n\x14GitOnBorgScmRevision\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04sha1\x18\x01 \x01(\t\"U\n\x10MultiScmRevision\x12\x41\n\x18git_on_borg_scm_revision\x18\x02 \x03(\x0b\x32\x1f.KokoroApi.GitOnBorgScmRevision\"\xc6\x01\n\x0b\x42uildResult\x12\x37\n\x12multi_scm_revision\x18\x0c \x01(\x0b\x32\x1b.KokoroApi.MultiScmRevision\x12\x17\n\x0f\x62uild_artifacts\x18\x02 \x03(\t\x12\x35\n\x08\x65nv_vars\x18\x0e \x03(\x0b\x32#.KokoroApi.BuildResult.EnvVarsEntry\x1a.\n\x0c\x45nvVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"U\n\x13\x42uildStatusResponse\x12\x10\n\x08\x62uild_id\x18\x05 \x01(\t\x12,\n\x0c\x62uild_result\x18\x02 \x01(\x0b\x32\x16.KokoroApi.BuildResult'
)




_GITONBORGSCMREVISION = _descriptor.Descriptor(
  name='GitOnBorgScmRevision',
  full_name='KokoroApi.GitOnBorgScmRevision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='KokoroApi.GitOnBorgScmRevision.name', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sha1', full_name='KokoroApi.GitOnBorgScmRevision.sha1', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=81,
)


_MULTISCMREVISION = _descriptor.Descriptor(
  name='MultiScmRevision',
  full_name='KokoroApi.MultiScmRevision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='git_on_borg_scm_revision', full_name='KokoroApi.MultiScmRevision.git_on_borg_scm_revision', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=168,
)


_BUILDRESULT_ENVVARSENTRY = _descriptor.Descriptor(
  name='EnvVarsEntry',
  full_name='KokoroApi.BuildResult.EnvVarsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='KokoroApi.BuildResult.EnvVarsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='KokoroApi.BuildResult.EnvVarsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=369,
)

_BUILDRESULT = _descriptor.Descriptor(
  name='BuildResult',
  full_name='KokoroApi.BuildResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='multi_scm_revision', full_name='KokoroApi.BuildResult.multi_scm_revision', index=0,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='build_artifacts', full_name='KokoroApi.BuildResult.build_artifacts', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='env_vars', full_name='KokoroApi.BuildResult.env_vars', index=2,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BUILDRESULT_ENVVARSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=369,
)


_BUILDSTATUSRESPONSE = _descriptor.Descriptor(
  name='BuildStatusResponse',
  full_name='KokoroApi.BuildStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='build_id', full_name='KokoroApi.BuildStatusResponse.build_id', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='build_result', full_name='KokoroApi.BuildStatusResponse.build_result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=456,
)

_MULTISCMREVISION.fields_by_name['git_on_borg_scm_revision'].message_type = _GITONBORGSCMREVISION
_BUILDRESULT_ENVVARSENTRY.containing_type = _BUILDRESULT
_BUILDRESULT.fields_by_name['multi_scm_revision'].message_type = _MULTISCMREVISION
_BUILDRESULT.fields_by_name['env_vars'].message_type = _BUILDRESULT_ENVVARSENTRY
_BUILDSTATUSRESPONSE.fields_by_name['build_result'].message_type = _BUILDRESULT
DESCRIPTOR.message_types_by_name['GitOnBorgScmRevision'] = _GITONBORGSCMREVISION
DESCRIPTOR.message_types_by_name['MultiScmRevision'] = _MULTISCMREVISION
DESCRIPTOR.message_types_by_name['BuildResult'] = _BUILDRESULT
DESCRIPTOR.message_types_by_name['BuildStatusResponse'] = _BUILDSTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GitOnBorgScmRevision = _reflection.GeneratedProtocolMessageType('GitOnBorgScmRevision', (_message.Message,), {
  'DESCRIPTOR' : _GITONBORGSCMREVISION,
  '__module__' : 'kokoro_api_pb2'
  # @@protoc_insertion_point(class_scope:KokoroApi.GitOnBorgScmRevision)
  })
_sym_db.RegisterMessage(GitOnBorgScmRevision)

MultiScmRevision = _reflection.GeneratedProtocolMessageType('MultiScmRevision', (_message.Message,), {
  'DESCRIPTOR' : _MULTISCMREVISION,
  '__module__' : 'kokoro_api_pb2'
  # @@protoc_insertion_point(class_scope:KokoroApi.MultiScmRevision)
  })
_sym_db.RegisterMessage(MultiScmRevision)

BuildResult = _reflection.GeneratedProtocolMessageType('BuildResult', (_message.Message,), {

  'EnvVarsEntry' : _reflection.GeneratedProtocolMessageType('EnvVarsEntry', (_message.Message,), {
    'DESCRIPTOR' : _BUILDRESULT_ENVVARSENTRY,
    '__module__' : 'kokoro_api_pb2'
    # @@protoc_insertion_point(class_scope:KokoroApi.BuildResult.EnvVarsEntry)
    })
  ,
  'DESCRIPTOR' : _BUILDRESULT,
  '__module__' : 'kokoro_api_pb2'
  # @@protoc_insertion_point(class_scope:KokoroApi.BuildResult)
  })
_sym_db.RegisterMessage(BuildResult)
_sym_db.RegisterMessage(BuildResult.EnvVarsEntry)

BuildStatusResponse = _reflection.GeneratedProtocolMessageType('BuildStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUILDSTATUSRESPONSE,
  '__module__' : 'kokoro_api_pb2'
  # @@protoc_insertion_point(class_scope:KokoroApi.BuildStatusResponse)
  })
_sym_db.RegisterMessage(BuildStatusResponse)


_BUILDRESULT_ENVVARSENTRY._options = None
# @@protoc_insertion_point(module_scope)
